#pragma once
#include "Component.h"
#include "BattleInstance.h"
#include "Buffs.h"
#include "UICanvas.h"
#include "Text2D.h"

enum TOWER_STATE
{
	NOT_IN_BATTLE,
	IN_BATTLE,
	IN_REWARDS
};

class TowerManager : public Odyssey::Component
{
	CLASS_DECLARATION(TowerManager);
	
public: // Constructors
	TowerManager() = default;
	virtual std::shared_ptr<Odyssey::Component> clone() const;
	virtual ~TowerManager();

	Odyssey::UICanvas* UI = nullptr;
	Odyssey::UICanvas* Rewards = nullptr;

	// TODO: REFACTOR LATER
	Odyssey::Scene* scene = nullptr;

public: // Functions

	// Necessary
	virtual void initialize();
	virtual void update(double deltaTime);
	
	void SetUpTowerManager(int _numberOfBattles);
	void CreateBattleInstance();
	void CreateTutorialInstance();
	
	//Getters
	int GetTowerState() { return mTowerState; }

	EntityList GetEnemyTeam() { return mEnemyTeam; } // This will allow the battle instance to get the enemy team genreated by the Overlord

	//std::shared_ptr<float> GetStatitics() { return mStatitics; } // This will return the statics that the Overlord will be using to construct a new enemy team

	int GetCurrentLevel() { return mCurrentLevel; }

	BattleInstance* GetBattleInstance() { return mCurrentBattle; }

	//Setters
	void SetTowerState(TOWER_STATE _newTowerState) { mTowerState = _newTowerState; }

	void SetTutorialState(bool state) { mIsTutorial = state; };

	void SetEnemyTeam(EntityList _newEnemyTeam) { mEnemyTeam = _newEnemyTeam; } // This will set the enemy team to the new enemy team that is generated by the Overlord

	void SetCurrentLevel(int _levelNum) { mCurrentLevel = _levelNum; }

private: // Varibales

	// Cheat Code Variables
	bool mUsedBossCheatCode = false;

	//Battle Instance
	BattleInstance* mCurrentBattle = nullptr;

	// Vectors
	EntityList mPlayerTeam; // playerTeam will hold the gameObjects associated with the Player's team
	EntityList mEnemyTeam; // enemyTeam will hold the gameObjects associated with the Overlord's team
	EntityList mListOfRoomObjects; // Hold the room objects
	Odyssey::Entity* mCharacterSpotLights[3] = { nullptr, nullptr, nullptr };

	// Queues

	// Entities
	Odyssey::Entity* tmTurnIndicator = nullptr; // This will be the object underneath the character who's turn it is

	// Ints
	int mCurrentLevel = 0;
	int mNumberOfLevels = 0;

	// Floats

	// Bools
	bool mIsPaused = false;
	bool mIsTutorial = false;

	// Tower State
	TOWER_STATE mTowerState = TOWER_STATE::NOT_IN_BATTLE;

private: // Functions
	void DestroyBattleInstance();
	void TogglePauseMenu();
	void ToggleCharacterUI(bool _onOrOff);
	void ShowOptionsMenu();
	void ShowControlScreen();
	void HideControlScreen();
	void GoToMainMenu();

	// Create the heros and all of their elements
	void CreateThePlayerTeam();
};

